import { expect, test } from '@playwright/test'

test('instructor renames a populated classroom, cancels deletion, then deletes it with confirmation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.getByRole('button', { name: /Explore as instructor/ }).click()
  const original = `Managed classroom ${Date.now()}`
  await page.getByLabel('Add classroom').fill(original)
  await page.getByLabel('Add classroom').press('Enter')
  await expect(page.getByRole('heading', { name: original, exact: true })).toBeVisible()
  const rooms = await page.request.get('http://127.0.0.1:8000/classrooms/', { headers: { Authorization: 'Bearer mock:teacher@example.edu' } })
  const id = (await rooms.json()).find((room: { name: string }) => room.name === original).id
  await page.getByRole('button', { name: /Manage classroom/ }).click()
  await page.getByLabel('Import student roster (CSV)').setInputFiles({ name: 'roster.csv', mimeType: 'text/csv', buffer: Buffer.from('email,groupname\nmanage@example.edu,Alpha') })
  await expect(page.getByText('Imported 1 students.', { exact: true })).toBeVisible()
  const renamed = `${original} renamed`
  await page.getByTestId('classroom-name').fill(renamed)
  await page.getByTestId('rename-classroom').click()
  await expect(page.getByRole('heading', { name: renamed, exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Classrooms' }).getByRole('button', { name: new RegExp(renamed) })).toBeVisible()
  await expect(page.getByText('Classroom renamed.', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('navigation', { name: 'Classrooms' }).getByRole('button', { name: new RegExp(renamed) }).click()
  await page.getByRole('button', { name: /Manage classroom/ }).click()
  let deletes = 0
  page.on('request', request => { if (request.method() === 'DELETE' && request.url().endsWith(`/classrooms/${id}`)) deletes++ })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByTestId('delete-classroom').click()
  const dialog = page.getByTestId('delete-classroom-dialog')
  await expect(dialog).toBeVisible()
  await expect(page.getByTestId('confirm-delete-classroom')).toBeDisabled()
  await page.getByTestId('confirm-classroom-name').fill('Wrong room')
  await expect(page.getByTestId('confirm-delete-classroom')).toBeDisabled()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(deletes).toBe(0)
  await expect(page.getByRole('heading', { name: renamed, exact: true })).toBeVisible()
  await page.getByTestId('delete-classroom').click()
  await page.getByTestId('confirm-classroom-name').fill(renamed)
  await page.getByTestId('confirm-delete-classroom').click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: renamed, exact: true })).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'Classrooms' }).getByRole('button', { name: new RegExp(renamed) })).toHaveCount(0)
  expect(deletes).toBe(1)
  await expect(page.getByRole('heading', { name: 'PairEval Demo', exact: true })).toBeVisible()
  const remaining = await page.request.get('http://127.0.0.1:8000/students/?classroom_id=' + id, { headers: { Authorization: 'Bearer mock:teacher@example.edu' } })
  expect(remaining.status()).toBe(404)
})

test('rename and deletion failures retain the room and allow a safe retry', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.getByRole('button', { name: /Explore as instructor/ }).click()
  await page.getByRole('button', { name: /Manage classroom/ }).click()
  await page.route('**/classrooms/*', async route => {
    if (['PATCH', 'DELETE'].includes(route.request().method())) return route.fulfill({ status: 503, json: { detail: 'Try again later.' } })
    await route.continue()
  })
  await page.getByTestId('classroom-name').fill('Failed rename')
  await page.getByTestId('rename-classroom').click()
  await expect(page.getByRole('status').filter({ hasText: 'Try again later.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'PairEval Demo', exact: true })).toBeVisible()
  await expect(page.getByTestId('rename-classroom')).toBeEnabled()
  await page.getByTestId('delete-classroom').click()
  await page.getByTestId('confirm-classroom-name').fill('PairEval Demo')
  await page.getByTestId('confirm-delete-classroom').click()
  await expect(page.getByRole('alert').filter({ hasText: 'Try again later.' })).toBeVisible()
  await expect(page.getByTestId('delete-classroom-dialog')).toBeVisible()
  await expect(page.getByTestId('confirm-delete-classroom')).toBeEnabled()
  await page.getByTestId('delete-classroom-dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'PairEval Demo', exact: true })).toBeVisible()
})
