import { expect, test } from '@playwright/test'

test('complete publication, submission, scores and exports with real API', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  let release!: () => void
  let pending = new Promise<void>(resolve => { release = resolve })
  await page.route('**/assignments/?*', async route => { await pending; await route.continue() })
  await page.getByRole('button', { name: /Explore as instructor/ }).click()
  await expect(page.getByText('Loading assignments...', { exact: true })).toBeVisible()
  await expect(page.getByText('No assignments yet.', { exact: true })).toHaveCount(0)
  release()
  await page.unrouteAll({ behavior: 'wait' })
  const classroom = `Complete flow ${Date.now()}`
  await page.getByLabel('Add classroom').fill(classroom)
  await page.getByLabel('Add classroom').press('Enter')
  await expect(page.getByRole('heading', { name: classroom, exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Manage classroom/ }).click()
  await page.getByLabel('Import student roster (CSV)').setInputFiles({ name: 'roster.csv', mimeType: 'text/csv', buffer: Buffer.from('email,groupname\n' + Array.from({ length: 9 }, (_, i) => `student${i + 1}@example.edu,${i >= 6 ? '=SUM(1)' : `Group ${Math.floor(i / 3)}`}`).join('\n')) })
  await expect(page.getByText(/Row 8: invalid group name/)).toBeVisible()
  await page.getByLabel('Import student roster (CSV)').setInputFiles({ name: 'safe-roster.csv', mimeType: 'text/csv', buffer: Buffer.from('email,groupname\n' + Array.from({ length: 9 }, (_, i) => `student${i + 1}@example.edu,Group ${Math.floor(i / 3)}`).join('\n')) })
  await expect(page.getByText('Imported 9 students.', { exact: true })).toBeVisible()
  const classroomList = await page.request.get('http://127.0.0.1:8000/classrooms/', { headers: { Authorization: 'Bearer mock:teacher@example.edu' } })
  const createdClassroom = (await classroomList.json()).find((item: { name: string }) => item.name === classroom)
  const legacyGroup = await page.request.post('http://127.0.0.1:8000/groups/', { headers: { Authorization: 'Bearer mock:teacher@example.edu' }, data: { name: '=SUM(1)', classroom_id: createdClassroom.id } })
  expect(legacyGroup.ok()).toBeTruthy()
  await page.locator('summary').filter({ hasText: 'Create assignment' }).click()
  const title = `Complete review ${Date.now()}`
  await page.getByLabel('Title', { exact: true }).fill(title)
  await page.getByRole('group', { name: 'Group evaluation', exact: true }).getByLabel('Deadline').fill(new Date(Date.now() + 86400000).toISOString().slice(0, 16))
  await page.getByRole('button', { name: 'Create assignment', exact: true }).click()
  await expect(page.getByText('Assignment created.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Preview pairs', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Pair assignment preview' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Hide preview', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: 'Hide preview', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Pair assignment preview' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Preview pairs', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('button', { name: 'Preview pairs', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Pair assignment preview' })).toBeVisible()
  await page.getByRole('button', { name: 'Hide preview', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Pair assignment preview' })).toHaveCount(0)
  let publishRequests = 0
  let assignmentApi = ''
  let failRefresh = false
  pending = new Promise<void>(resolve => { release = resolve })
  await page.route('**/assignments/?*', async route => {
    if (failRefresh) { failRefresh = false; await route.fulfill({ status: 503, body: '{"detail":"Temporary refresh failure"}', contentType: 'application/json' }) }
    else await route.continue()
  })
  await page.route('**/publish', async route => {
    assignmentApi = route.request().url().replace(/\/publish$/, '')
    publishRequests++; await pending
    const response = await route.fetch()
    failRefresh = true
    await route.fulfill({ response })
  })
  const publish = page.locator('.publish-action')
  await publish.click()
  await expect(publish).toBeDisabled()
  await expect(publish).toHaveAttribute('aria-busy', 'true')
  await expect(page.getByRole('button', { name: 'Preview pairs', exact: true })).toBeDisabled()
  expect(publishRequests).toBe(1)
  release()
  await expect(page.getByText('Published', { exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Temporary refresh failure')
  await expect(page.locator('.publish-action')).toHaveCount(0)
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: /Sign out/ }).click()
  await page.getByRole('button', { name: /Explore as student/ }).click()
  await page.getByRole('button', { name: new RegExp(classroom) }).click()
  const evaluation = page.getByRole('heading', { name: 'Group evaluation', exact: true }).locator('..')
  await evaluation.locator('input[type=radio]').first().click()
  await expect(evaluation.getByText('Draft saved.', { exact: true })).toBeVisible()
  await evaluation.getByRole('button', { name: 'Submit saved answers', exact: true }).click()
  await evaluation.getByRole('button', { name: 'Confirm submission', exact: true }).click()
  await expect(evaluation.getByText(/Submitted 1 of/)).toBeVisible()
  await page.locator('summary').filter({ hasText: 'Scores and coverage' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  const forbiddenReport = await page.request.get(`${assignmentApi}/report`, { headers: { Authorization: 'Bearer mock:student1@example.edu' } })
  expect(forbiddenReport.status()).toBe(403)
  const outsider = await page.request.get(`${assignmentApi}/evaluation/group`, { headers: { Authorization: 'Bearer mock:outsider@example.edu' } })
  expect(outsider.status()).toBe(403)
  await page.getByRole('button', { name: /Sign out/ }).click()
  await page.getByRole('button', { name: /Explore as instructor/ }).click()
  await page.getByRole('button', { name: new RegExp(classroom) }).click()
  let reportReads = 0
  page.on('request', request => { if (/\/report$/.test(request.url())) reportReads++ })
  await page.locator('summary').filter({ hasText: 'Scores and coverage' }).click()
  await expect(page.getByRole('table').filter({ has: page.getByRole('columnheader', { name: 'Student', exact: true }) }).locator('tbody tr')).toHaveCount(9)
  expect(reportReads).toBeGreaterThan(0)
  for (const name of ['Export groups CSV', 'Export students CSV', 'Export pairs CSV', 'Export Excel']) {
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name, exact: true }).click()
    const exported = await download
    expect(exported.suggestedFilename()).toMatch(/\.(csv|xlsx)$/)
    if (name.endsWith('CSV')) {
      const stream = await exported.createReadStream()
      expect(stream).not.toBeNull()
      const chunks: Buffer[] = []
      for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
      const content = Buffer.concat(chunks).toString('utf8')
      if (name === 'Export groups CSV') expect(content).toContain("'=SUM(1)")
      if (name === 'Export pairs CSV') expect(content).not.toContain('@example.edu')
    }
  }
  await page.getByRole('button', { name: /Manage classroom/ }).click()
  await page.getByText('Move student between groups', { exact: true }).click()
  await page.getByLabel('Choose student').selectOption({ label: 'student1@example.edu (Group 0)' })
  await page.getByLabel('Target group').selectOption({ label: 'Group 1' })
  await page.getByRole('button', { name: 'Move', exact: true }).click()
  pending = new Promise<void>(resolve => { release = resolve })
  await page.route('**/students/*/group', async route => { await pending; await route.continue() })
  await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Moving...', exact: true })).toBeDisabled()
  release()
  await expect(page.getByText(/Moved student\./)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Recent moves', exact: true })).toBeVisible()
  await expect(page.getByLabel('Choose student').locator('option:checked')).toHaveText('student1@example.edu (Group 1)')
})
