import { expect, test } from '@playwright/test'

test('action notices are readable mobile toasts, repeatable and dismissible', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 640 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.getByRole('button', { name: /Explore as instructor/ }).click()
  await page.getByRole('button', { name: /Manage classroom/ }).click()
  const input = page.getByLabel('Classroom name', { exact: true })
  const original = await input.inputValue()
  const toast = page.getByTestId('action-toast')
  for (const name of [original + ' toast', original]) {
    await input.fill(name)
    await page.getByRole('button', { name: 'Save classroom name' }).click()
    await expect(toast.getByRole('status')).toHaveText('Classroom renamed.')
    expect(await toast.evaluate(element => getComputedStyle(element).position)).toBe('fixed')
    expect(await toast.evaluate(element => getComputedStyle(element).animationName)).toBe('none')
    const bounds = await toast.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
    expect(bounds!.y + bounds!.height).toBeCloseTo(624, 0)
    await toast.getByRole('button', { name: 'Dismiss notification' }).focus()
    await page.keyboard.press('Escape')
    await expect(toast).toBeHidden()
  }
  await input.fill(original + ' auto-dismiss')
  await page.getByRole('button', { name: 'Save classroom name' }).click()
  await expect(toast).toBeVisible()
  await expect(toast).toBeHidden({ timeout: 10000 })
  await input.fill(original)
  await page.getByRole('button', { name: 'Save classroom name' }).click()
  await expect(toast).toBeVisible()
  await toast.getByRole('button', { name: 'Dismiss notification' }).click()
  await expect(toast).toBeHidden()
})
